### ISSUE TITLE
Error while importing torch

### ISSUE THREAD

**Issue by ShivaniSSS** [tinkerhub-org/ComputerVision-with-PyTorch-Learning-Program#45]
## Specific Question
The installation was successful, but importing torch throws an error. I have added anaconda's path to environment variable and tried a lot, but still no change.
## OS, package manager and PyTorch Version
> Add the following details.
* OS - Windows
* PyTorch Version - Stable(1.5)
* Package Manager - conda

## Complete Error Log
` ` ` Traceback (most recent call last):
  File "c:/Users/Shivani/Desktop/pytorch1.py", line 2, in <module>
    import torch
  File "C:\Users\Shivani\anaconda3\lib\site-packages\torch\__init__.py", line 81, in <module>
    ctypes.CDLL(dll)
  File "C:\Users\Shivani\anaconda3\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found ` ` `

**Comment by humandotlearning** [comment]
@ShivaniSSS is this issue solved?
