### ISSUE TITLE
Error while importing SummaryWriter

### ISSUE THREAD

**Issue by fausan123** [tinkerhub-org/ComputerVision-with-PyTorch-Learning-Program#59]
## Specific Question
 An error occurred while importing SummaryWriter from torch.utils.tensorboard 
## OS, package manager and PyTorch Version
* OS - Ubuntu 18.04
* PyTorch Version - 1.5
* Package Manager - conda

## Complete Error Log
``` 
Traceback (most recent call last):
  File "/home/fausan/anaconda3/lib/python3.7/site-packages/torch/utils/tensorboard/__init__.py", line 2, in <module>
    from tensorboard.summary.writer.record_writer import RecordWriter  # noqa F401
  File "/home/fausan/Desktop/Pytorch-CV/tensorboard.py", line 2, in <module>
    from torch.utils.tensorboard import SummaryWriter
ImportError: cannot import name 'SummaryWriter' from 'torch.utils.tensorboard' (/home/fausan/anaconda3/lib/python3.7/site-packages/torch/utils/tensorboard/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tensorboard.py", line 2, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/home/fausan/anaconda3/lib/python3.7/site-packages/torch/utils/tensorboard/__init__.py", line 4, in <module>
    raise ImportError('TensorBoard logging requires TensorBoard with Python summary writer installed. '
ImportError: TensorBoard logging requires TensorBoard with Python summary writer installed. This should be available in 1.14 or above.

```

**Comment by gksoriginals** [comment]
Can you try [this](https://github.com/pytorch/pytorch/issues/20140) @fausan123

**Comment by fausan123** [comment]
The above error seems to be fixed after opening file in a different directory (donno why), but now a new error is showing :

```
Traceback (most recent call last):
  File "new.py", line 68, in <module>
    writer = SummaryWriter('runs/fashion_mnist_experiment_1')
  File "/home/fausan/anaconda3/lib/python3.7/site-packages/torch/utils/tensorboard/writer.py", line 225, in __init__
    self._get_file_writer()
  File "/home/fausan/anaconda3/lib/python3.7/site-packages/torch/utils/tensorboard/writer.py", line 256, in _get_file_writer
    self.flush_secs, self.filename_suffix)
  File "/home/fausan/anaconda3/lib/python3.7/site-packages/torch/utils/tensorboard/writer.py", line 66, in __init__
    log_dir, max_queue, flush_secs, filename_suffix)
  File "/home/fausan/anaconda3/lib/python3.7/site-packages/tensorboard/summary/writer/event_file_writer.py", line 76, in __init__
    if not tf.io.gfile.exists(logdir):
  File "/home/fausan/anaconda3/lib/python3.7/site-packages/tensorboard/lazy.py", line 68, in __getattr__
    return getattr(load_once(self), attr_name)
AttributeError: module 'tensorflow' has no attribute 'io'
```

**Comment by fausan123** [comment]
@GopikrishnanSasikumar The above error seems to be fixed after opening file in a different directory (donno why), but now a new error is showing :

```
Traceback (most recent call last):
  File "new.py", line 68, in <module>
    writer = SummaryWriter('runs/fashion_mnist_experiment_1')
  File "/home/fausan/anaconda3/lib/python3.7/site-packages/torch/utils/tensorboard/writer.py", line 225, in __init__
    self._get_file_writer()
  File "/home/fausan/anaconda3/lib/python3.7/site-packages/torch/utils/tensorboard/writer.py", line 256, in _get_file_writer
    self.flush_secs, self.filename_suffix)
  File "/home/fausan/anaconda3/lib/python3.7/site-packages/torch/utils/tensorboard/writer.py", line 66, in __init__
    log_dir, max_queue, flush_secs, filename_suffix)
  File "/home/fausan/anaconda3/lib/python3.7/site-packages/tensorboard/summary/writer/event_file_writer.py", line 76, in __init__
    if not tf.io.gfile.exists(logdir):
  File "/home/fausan/anaconda3/lib/python3.7/site-packages/tensorboard/lazy.py", line 68, in __getattr__
    return getattr(load_once(self), attr_name)
AttributeError: module 'tensorflow' has no attribute 'io'
```

**Comment by fausan123** [comment]
Reinstalling datasets in a new directory seems to fix the issue
