### ISSUE TITLE
Error installing Tensorboard in colab

### ISSUE THREAD

**Issue by Jaseemck** [tinkerhub-org/ComputerVision-with-PyTorch-Learning-Program#75]
## Specific Question
> Following this [write-up](https://medium.com/looka-engineering/how-to-use-tensorboard-with-pytorch-in-google-colab-1f76a938bc34) to begin with tensorboard in colab notebook. But whenever I run this code, `!pip install -q tf-nightly-2.0-preview`, it gives an error:

## OS, package manager and PyTorch Version
> Default colab environment

## Complete Error Log
> ERROR: Could not find a version that satisfies the requirement tf-nightly-2.0-preview (from versions: none)
ERROR: No matching distribution found for tf-nightly-2.0-preview

**Comment by gksoriginals** [comment]
@Jaseemck can you try this ?
```
!pip install -q tf-nightly
```

**Comment by Jaseemck** [comment]
**_It worked. But the code forth gave me errors:_**

### code:

> `%load_ext tensorboard`
> `%tensorboard --logdir logs/tensorboard`

### Error log:

> ERROR: Failed to launch TensorBoard (exited with 1).
Contents of stderr:
2020-06-16 02:14:41.237938: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "/usr/local/bin/tensorboard", line 8, in <module>
    sys.exit(run_main())
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/main.py", line 75, in run_main
    app.run(tensorboard.main, flags_parser=tensorboard.configure)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/program.py", line 290, in main
    return runner(self.flags) or 0
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/program.py", line 306, in _run_serve_subcommand
    server = self._make_server()
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/program.py", line 416, in _make_server
    ingester.deprecated_multiplexer,
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/backend/application.py", line 129, in TensorBoardWSGIApp
    tbplugins, flags.path_prefix, data_provider, experimental_plugins
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/backend/application.py", line 226, in __init__
    "Duplicate plugins for name %s" % plugin.plugin_name
ValueError: Duplicate plugins for name projector

**Comment by Jaseemck** [comment]
**FYI**, the code was `%load_ext tensorboard.notebook` as per [write-up](https://medium.com/looka-engineering/how-to-use-tensorboard-with-pytorch-in-google-colab-1f76a938bc34). But the log gives:

> RuntimeError: Use '%load_ext tensorboard' instead of '%load_ext tensorboard.notebook'.
**_Hence changed and that code is used above._**

**Comment by Jaseemck** [comment]
### Solution: These codes could solve the issue:
**Should have installed tensorflow 2.0.0**
` !pip install tensorflow==2.0.0-alpha0`
`from tensorflow import summary`
`%load_ext tensorboard.notebook`
`%tensorboard --logdir run`

> These could launch the tensorboard in colab.
Thanks @rinsacm for the helping hand.
